### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by MasterMedo**
While reading the style guide I found some spelling typos, so I corrected them.

I checked other markdown files in the repository but they were fine. On the other hand I noticed a lot of trailing newlines at the end of the files. I can remove those but to what avail if they're going to keep popping up.

### CODE REVIEW

**Comment by mfrancekovic** [comment]
@MasterMedo thanks for the typo fixes.

About the line endings, I've had a lot of problems with Windows and line endings. Although I've never worked on this repo I can imagine the line endings are messy because of the cross-platform development (by that I mean dev's using Windows :p).

**Comment by MasterMedo** [comment]
That can be avoided with extensions and scripts. Windows doesn't add newlines to the end of files. Text editors do :)

**Comment by mfrancekovic** [comment]
That's actually not true. Git on Windows changes the line endings depending on the git configuration.

`core.autocrlf = true` => default for Windows, automatically changes all line endings to \r\n on checkout. Meaning if you have a repo that has LF for line endings, after you checkout on windows, everything will be changed to CRLF.

You can read more about that here: https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows

But there are other discussions available online as well.

**Comment by MasterMedo** [comment]
I'm talking about files that have lines like: `some text        ` (notice the trailing spaces), or end in `\n\n\n\n\n\n`

**Comment by mfrancekovic** [comment]
That's a different thing for sure. 👍 

I wouldn't spend much time for now on this repo, as we will be rethinking the approach used in this repo in the short term.

**Comment by MasterMedo** [comment]
I think this should be merged non the less, the typos are obvious :)
And everyone should be using some kind of a spellchecking software.

**Comment by mfrancekovic** [comment]
I agree! 

I guess there is no one in charge of this repo except Buda. So I propose you assign me as a reviewer and I'll see if I can approve it.

Although I see there is no obstacle from merging this except for courtesy :)

**Review by mfrancekovic — APPROVED** [review]
👍

**Pull request merged**
